AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources: 
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: index.handler
      CodeUri: 
        Bucket: dolapo-dynamodb2
        Key: dolapodb2-6ffe3342-6982-4d52-8b38-1c76c40c85c2.zip
        MyS3Upload:
          Type: S3
          Properties:
            Bucke: !Ref MyS3Bucket
            Events: s3:ObjectCreated:*
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: handleruploadbaby2387654
