AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources: 
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: index.handler
      CodeUri: 
        Bucket: dolapo-dynamodb3
        Key: dolapodb3-8af9771a-e378-40e6-b41b-b9c67f5a4c70.zip
        Architectures:
        - x86_64
      Events:
        HelloWorld2:
          Type: Api
          Properties:
            Path: /items
            Method: get
