AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources: 
  MyLambdaFunctionOverHttps:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: index.handler
      CodeUri: 
        Bucket: dolapo-oigapi
        Key: HelloWorld-01b123d6-d332-4840-b9cd-211c6848c6c0.zip
      Events:
        MyApiResources:
          Type: API
          Properties:
            Path: /my-resource
            Method: get
