AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources: 
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: index.handler
      CodeUri: 
        Bucket: dolapo-oigapi
        Key: HelloWorld-01b123d6-d332-4840-b9cd-211c6848c6c0.zip
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: API
          Properties:
            Path: /hello
            Method: get
