AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources: 
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      Handler: index.handler
      CodeUri: 
        Bucket: dolapo-blue
        Key: dolapo-blue-a62e9506-3b3f-4ac7-9e80-bb7e94acba5c.zip
        Architectures:
        - x86_64
      Events:
        HelloWorld2:
          Type: Api
          Properties:
            Path: /hello
            Method: get
