version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::318775028588:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-CE210HSJQV9A"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::318775028588:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1M2G3SMWM4JLB"
cloudformation_execution_role = "arn:aws:iam::318775028588:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-5FOX47GZWM6H"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-gxrlz0xuet5d"
image_repository = "318775028588.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-2f5dquabctqd"
region = "us-east-1"

[stage]
[stage.pipeline_bootstrap]
[stage.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::318775028588:role/aws-sam-cli-managed-stage-pi-PipelineExecutionRole-1BW6CDI4LRDZE"
cloudformation_execution_role = "arn:aws:iam::318775028588:role/aws-sam-cli-managed-stage-CloudFormationExecutionR-TKEE97OKS0C0"
artifacts_bucket = "aws-sam-cli-managed-stage-pipelin-artifactsbucket-pj0x5hunywa2"
image_repository = "318775028588.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-stage-pipeline-resources-imagerepository-ergt2ceox3f3"
region = "us-east-1"
